sudo: false
dist: trusty
language: node_js
node_js:
- node
- 7
cache: yarn
services:
- mysql
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- yarn webdriver-manager update
- mysql < server/test/init.sql
script:
- yarn gulp testPrep
- yarn test:server
- yarn test:client
after_success: gulp coveralls
addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
